cat("==========================================================================")
install.packages("RSclient_0.7-2.tar.gz", repos=NULL, type="source")
cat("==========================================================================")
install.packages("CEMS.tar.gz", repos=NULL, type="source")
cat("==========================================================================")
install.packages("shiny_0.13.0.tar.gz", repos=NULL, type="source")
cat("==================     R Packages install complete.     ==================")
library(CEMS)