cat("====================     R Packages install start     ====================")
install.packages("plyr", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("rjson", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("rmongodb", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("rJava", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("forecast", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("googleVis", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("ggplot2", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("timeSeries", repos="http://cran.nexr.com/")
cat("==========================================================================")
install.packages("dygraphs", repos="http://cran.nexr.com/")
cat("==========================================================================")